ope = open("file2.txt","r")
re = ope.read()
print(re)
ope.close()
ope = open("file2.txt","r")
for i in ope:
    print(i)
ope.close()
ope = open("file2.txt","r")
re = ope.read(3)
print(re)
ope.close()
ope = open("file2.txt","w")
ope.write("Bye\n")
ope.write("Morning\n")
ope.close()
ope = open("file2.txt","a")
ope.write("no")
ope.close()